name: reddit-playlist
dependencies:
- python=3
- requests=2.12.4
- flask=0.12.2
- gunicorn=19.1.0
- psycopg2=2.7.1
- pip
- pip:
    - google-api-python-client==1.6.2
    - httplib2==0.10.3
    - oauth2client==4.1.2
